{
 "title": "Traefik Dashboard",
 "description": "Traefik dashboard prometheus",
 "tags": [ "Provisioned" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request by $service over $interval",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$service\"}[$interval])) by (code, service)",
     "legendFormat": "{{ service }} - {{ code }}"
    }
   ]
  },
  {
   "title": "Bad Requests averaged over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code!~\"[2|3]..\"}[$interval])) by (service, code)",
     "legendFormat": "{{ code }}: {{ service }}"
    }
   ]
  },
  {
   "title": "Average latency by backend over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_sum{protocol=\"http\"}[$interval])) by (service) / sum(rate(traefik_service_request_duration_seconds_count{protocol=\"http\"}[$interval])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Latency percentiles for \"$service\" averaged over $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[$interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[$interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[$interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$service\"}[$interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  }
 ]
}